### ISSUE TITLE
Injecting global data into responses

### ISSUE THREAD

**Issue by joshbedo** [krakenjs/krakenjs.github.io#36]
I was wondering if there was any way to inject data like navigation or products into every response. I've seen something similar done with the passport example but i'm not quite sure if it would work the same way, wondering if their are any patterns i should be looking into. Otherwise i'd have to add an additional fetch to each route for something i realistically should be caching. Thanks!

**Comment by jasisk** [comment]
I'm not sure I fully understand the question. Is this data you want in the context that is passed to your templates? If so, there exists an `app.locals` which is merged with `res.locals` before being passed to your templates.

Otherwise, each response is going to be unique. You can certainly merge in anything you like. For example, having a middleware such as the following is a inexpensive operation and accomplishes what I think you may be asking:

``` js
var globalish = Object.freeze({x123: 'shoes'});

module.exports = function myMiddleware(req, res, next) {
  Object.defineProperty(req, 'products', {value: globalish});
  next();
};
```

Not that this isn't necessarily a pattern I'd promote but this should give you an idea.

Am I along the right lines of what you're asking?

**Comment by aredridel** [comment]
Or `req.products = globalish` for short ;-)

**Comment by jasisk** [comment]
> Or req.products = globalish for short ;-)

Yup. Just be aware of what's happening downstream of that middleware. Surprise mutation, particularly when dealing with an object that is shared across every request, is a nasty thing.
